Spores/Models/AnatomyModel.cs
namespace Spores.Models
{
    public class AnatomyModel
    {
    }
}

Spores/Models/DlookalikeModel.cs
namespace Spores.Models
{
    public class DlookalikeModel
    {
    }
}

Spores/Models/GlossaryModel.cs
namespace Spores.Models
{
    public class GlossaryModel
    {
    }
}

Spores/Models/Home.cs
namespace Spores.Models
{
    public class Home
    {
    }
}

Spores/Models/ListMushroomModel.cs
namespace Spores.Models
{
    public class ListMushroomModel
    {
    }
}

Spores/Controllers/AnatomyController.cs
using Microsoft.AspNetCore.Mvc;

namespace Spores.Controllers
{
    public class AnatomyController : Controller
    {
        public IActionResult Anatomy()
        {
            return View();
        }
    }
}

Spores/Controllers/DlookalikeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Spores.Controllers
{
    public class DlookalikeController : Controller
    {
        public IActionResult Dlookalike()
        {
            return View();
        }
    }
}

Spores/Controllers/GlossaryController.cs
using Microsoft.AspNetCore.Mvc;

namespace Spores.Controllers
{
    public class GlossaryController : Controller
    {
        public IActionResult Glossary()
        {
            return View();
        }
    }
}

Spores/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Spores.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Spores/Controllers/ListMushroomController.cs
using Microsoft.AspNetCore.Mvc;

namespace Spores.Controllers
{
    public class ListMushroomController : Controller
    {
        public IActionResult ListMushroom()
        {
            return View();
        }
    }
}

Spores/Views/Anatomy/Anatomy.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<p>Anatomy will be updated</p>

Spores/Views/Dlookalike/Dlookalike.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Dangerous Look A-Likes will be updated</p>

Spores/Views/Glossary/Glossary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Glossary will be updated</p>

Spores/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Spores!</h1>
    <p>Learn about mushrooms and their characteristics</p>
</div>


<div class="d-flex bd-highlight">
    <div class="p-2 flex-fill bd-highlight">
        <div class="bg-light border-light" id="sidebar">
            <div class="sidebar-header text-center">Edible Mushrooms</div>
            <div class="list-group list-group-flush">
                <a href="#" class="list-group-item list-group-item-action bg-light">Morels</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Chanterelles</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Puffballs</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Oyster Mushrooms</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Chicken of the Woods</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Hen of the Woods</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Lions Mane</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Turkey Tail</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Honey Mushroom</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Lobster Mushroom</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Black Trumpet</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Pheasant's Back'</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Wood Ear</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Reishi</a>
            </div>
        </div>
    </div>
    

    <div class="p-2 flex-fill bd-highlight">
        <img src="~/Images/SporesImg.png" class="rounded mx-auto d-block align-content-center" alt="SporesImg"><br />
        <p>
            This website will be used to help new foragers to identify the mushrooms in the area of Gainesville, FL and to
            learn about the different components of mushrooms. This will be for educational purposes only. This site is
            meant to help new foragers to rule out possibilities by having the user specify the characteristics of the
            unidentifies mushroom. Mushroom hunting can be an enjoyable experience; but please do not ingest any
            mushrooms that you cannot 100% positively ID. Be safe, and happy hunting!
        </p><br />
    </div>


    <div class="p-2 flex-fill bd-highlight">
        <div class="bg-light border-light" id="sidebar">
            <div class="sidebar-header text-center">Caps/Gills/Veils</div>
            <div class="list-group list-group-flush">
                <a href="#" class="list-group-item list-group-item-action bg-light">Cap Shapes</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Cap Surfaces</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Cap Margins</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Gill Attachments</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Gill Spacing</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Veil and Annulus</a>
            </div>
        </div>
        <div class="mt-auto p-2 bd-highlight">
            <div class="bg-light border-light" id="bottom-sidebar">Common Apps:
                <div class="list-group list-group-flush">
                    <p>Fungi Identifier</p>
                    <p>Shrommify</p>
                    <p>ShroomID</p>
                </div>
            </div>
            
        </div>
    </div>
</div>   

Spores/Views/ListMushroom/ListMushroom.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>List of Mushrooms in Gainesville will be updated</p>

Spores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spores</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse text-center">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anatomy" asp-action="Anatomy">Anatomy of a Mushroom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dlookalike" asp-action="Dlookalike">Dangerous Look A-Likes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Glossary" asp-action="Glossary">Glossary of Terms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListMushroom" asp-action="ListMushroom">List of Mushrooms in Gainesville</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Spores - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>